package com.app567go.constant;

public enum AppState
{
	IN_HOME_SECTION,
	IN_PHOTO_ITEM_SECTION,
	IN_LAUNCH_PAGE,
	IN_INSTITUTE_INTRODUCTION_SECTION,
	IN_INSTITUTE_NEWS_SECTION,
	IN_INSTITUTE_MOMENT_SECTION,
	IN_FREQUENT_QUESTION_SECTION,
	IN_COURSE_SECTION,
	IN_MENTOR_SECTION,
	IN_RECRUITMENT_NEWS_SECTION,
	IN_ONLINE_SIGN_UP_SECTION,
	IN_CONTACT_US_SECTION,
}
