package com.app567go.constant;

public enum Command
{
	INITIALIZE,
	
	HOME_SECTION_TO_INSTITUTE_INTRODUCTION_SECTION,
	HOME_SECTION_TO_INSTITUTE_NEWS_SECTION,
	HOME_SECTION_TO_INSTITUE_MOMENT_SECTION,
	HOME_SECTION_TO_FREQUENT_QUESTION_SECTION,
	HOME_SECTION_TO_COURSE_SECTION,
	HOME_SECTION_TO_MENTOR_SECTION,
	HOME_SECTION_TO_RECRUITMENT_NEWS_SECTION,
	HOME_SECTION_TO_ONLINE_SIGN_UP_SECTION,
	HOME_SECTION_TO_CONTACT_US_SECTION,
	
	BACK_TO_HOME_SECTION,
	
	SHOW_WEB_CONTENT,
	
	LOGO_IMAGE_PRESSED,
	ONE_KEY_SHARE,
	
	ORIENTATION_CHANGED,
	
	START_ACTIVITY,
	
	START_LOADING_WEB_PAGE,
	FINISH_LOADING_WEB_PAGE,
	
	QUIT,
}